name: authentik
services:
  postgresql:
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    user: "999:999"
    image: docker.io/library/postgres:18.4-alpine3.24@sha256:9a8afca54e7861fd90fab5fdf4c42477a6b1cb7d293595148e674e0a3181de15
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    healthcheck:
      interval: 10s
      retries: 30
      start_period: 10s
      test: pg_isready -h 127.0.0.1 -p 5432 -U $$POSTGRES_USER -d $$POSTGRES_DB
      timeout: 5s
    volumes:
      - type: bind
        source: ${VOLUME_DB_SRC}
        target: ${VOLUME_DB_DST}
        read_only: false
    networks:
      - authentik

  authentik:
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    user: "568:568"
    image: ghcr.io/goauthentik/server:2026.5.5@sha256:50a833c48a714709f15d4f8846ec6b81a41d0d6a6bd2975087dfed3000d0d72e
    command: server
    restart: unless-stopped
    shm_size: 512mb
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      TZ: Europe/Berlin
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__NAME: "${POSTGRES_DB}"
      AUTHENTIK_POSTGRESQL__USER: "${POSTGRES_USER}"
      AUTHENTIK_POSTGRESQL__PASSWORD: "${POSTGRES_PASSWORD}"
      AUTHENTIK_SECRET_KEY: "${AUTHENTIK_SECRET_KEY}"
      AUTHENTIK_ERROR_REPORTING__ENABLED: "false"
      AUTHENTIK_DISABLE_UPDATE_CHECK: "true"
    healthcheck:
      interval: 10s
      retries: 30
      start_period: 60s
      test: ["CMD", "ak", "healthcheck"]
      timeout: 5s
    volumes:
      - type: bind
        source: ${VOLUME_DATA_SRC}
        target: ${VOLUME_DATA_DST}
        read_only: false
      - type: bind
        source: ${VOLUME_TEMPLATES_SRC}
        target: ${VOLUME_TEMPLATES_DST}
        read_only: false
    networks:
      - authentik
      - reverse-proxy

  worker:
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    user: "568:568"
    image: ghcr.io/goauthentik/server:2026.5.5@sha256:50a833c48a714709f15d4f8846ec6b81a41d0d6a6bd2975087dfed3000d0d72e
    command: worker
    restart: unless-stopped
    shm_size: 512mb
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      TZ: Europe/Berlin
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__NAME: "${POSTGRES_DB}"
      AUTHENTIK_POSTGRESQL__USER: "${POSTGRES_USER}"
      AUTHENTIK_POSTGRESQL__PASSWORD: "${POSTGRES_PASSWORD}"
      AUTHENTIK_SECRET_KEY: "${AUTHENTIK_SECRET_KEY}"
      AUTHENTIK_ERROR_REPORTING__ENABLED: "false"
      AUTHENTIK_DISABLE_UPDATE_CHECK: "true"
    healthcheck:
      interval: 10s
      retries: 30
      start_period: 60s
      test: ["CMD", "ak", "healthcheck"]
      timeout: 5s
    volumes:
      - type: bind
        source: ${VOLUME_DATA_SRC}
        target: ${VOLUME_DATA_DST}
        read_only: false
      - type: bind
        source: ${VOLUME_CERTS_SRC}
        target: ${VOLUME_CERTS_DST}
        read_only: false
      - type: bind
        source: ${VOLUME_TEMPLATES_SRC}
        target: ${VOLUME_TEMPLATES_DST}
        read_only: false
    networks:
      - authentik

networks:
  authentik:
  reverse-proxy:
    external: true
    name: reverse-proxy
