name: paperless-ngx-tools
services:
  gotenberg:
    command:
      - gotenberg
      - '--chromium-disable-javascript=true'
      - '--chromium-allow-list=file:///tmp/.*'
    image: docker.io/gotenberg/gotenberg:8.13
    restart: unless-stopped
    networks:
      - paperless-ngx
  tika:
    image: docker.io/apache/tika:3.0.0.0
    restart: unless-stopped
    networks:
      - paperless-ngx

networks:
  paperless-ngx:
      external: true
      name: ix-paperless-ngx_default