name: minio
services:
  minio:
    user: 473:473
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z
    restart: unless-stopped
    command:
      - server
      - --console-address
      - :9002
      - --address
      - :9000
    cap_drop: [ALL]
    security_opt:
      - no-new-privileges
    healthcheck:
      interval: 5s
      timeout: 5s
      retries: 5
      test: 
        - CMD 
        - mc
        - ready
        - local
    environment:
      MINIO_DOMAIN: ${MINIO_DOMAIN}
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_VOLUMES: ${VOLUME_DATA_DST}
      TZ: Etc/UTC
    volumes: 
    - type: bind
      source: ${VOLUME_DATA_SRC}
      target: ${VOLUME_DATA_DST}
      read_only: false
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
    name: nginx-proxy-manager_reverse-proxy