name: nginx-proxy-manager

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.12.1
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
      DB_SQLITE_FILE: ${VOLUME_DATA_DST}/database.sqlite
      DISABLE_IPV6: 'true'
      PUID: 568
      PGID: 568
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
    networks:
      - reverse-proxy
      - reverse-proxy-external
    volumes:
      - type: bind
        source: ${VOLUME_DATA_SRC}
        target: ${VOLUME_DATA_DST}
      - type: bind
        source: ${VOLUME_CERT_SRC}
        target: ${VOLUME_CERT_DST}

networks:
  reverse-proxy:
    driver: bridge
    internal: true
  reverse-proxy-external:
    driver: macvlan
    driver_opts:
      parent: ${PARENT_INTERFACE}
    ipam:
      config:
        - subnet: ${SUBNET}
          ip_range: ${IP_PUBLIC}/32
          gateway: ${GATEWAY}
